version: "3.9"


services:

  csserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: csserver
    container_name: csserver
    restart: always
    ports:
      - 27015:27015/udp

  mysql:
    image: mysql
    container_name: csserver-mysql
    restart: always
    ports:
      - 27006:3306
    environment:
      MYSQL_ROOT_PASSWORD: TralalaTrololo
      MYSQL_DATABASE: csserver
