version: "3.9"


volumes:
  home:


services:

  csserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: csserver
    container_name: csserver
    restart: always
    volumes:
      - home:/home/csserver
    ports:
      - 27015:27015/udp

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 27306:3306
    environment:
      MYSQL_ROOT_PASSWORD: TralalaTrololo
      MYSQL_DATABASE: csserver

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - home:/csserver:ro
      - ./nginx/conf.d/csserver.conf:/etc/nginx/conf.d/csserver.conf:ro
    ports:
      - 8016:8016
