version: "3.9"


volumes:
  home:


services:

  csserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: csserver
    container_name: csserver
    restart: always
    volumes:
      - home:/home/csserver
    ports:
      - 27015:27015/udp

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--sql_mode="
    ports:
      - 3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: TralalaTrololo
      MYSQL_DATABASE: csserver

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: php-fpm-alpine
    container_name: php
    restart: always
    ports:
      - 9016:9000

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - home:/csserver:ro
      - ./nginx/conf.d/csserver.conf:/etc/nginx/conf.d/csserver.conf:ro
      - ./csx_stats:/csx_stats:ro
    ports:
      - 8016:8016
