//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/fy_granja.html
halflife.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
models/chick.mdl
sound/misc/killchicken.wav
maps/fy_granja.bsp
maps/fy_granja.txt
