// for pwrfactory.spb.ru
gfx/env/morningdewup.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewft.tga
gfx/env/morningdewbk.tga
sprites/xffloor.spr
models/pwr_factory/dragon.mdl
models/pwr_factory/blue_flag.mdl
models/pwr_factory/guard.mdl
models/pwr_factory/monster.mdl
models/pwr_factory/fish2.mdl
models/pwr_factory/telega.mdl
models/pwr_factory/armstand.mdl
models/pwr_factory/crystal.mdl
models/pwr_factory/red_flag.mdl
sound/pwr_factory/start.wav
sound/pwr_factory/mystyc.wav
sound/pwr_factory/lovushka.wav
